spring:
   application:
      name: eureka-producer
eureka:
   client:
      service-url:
         defaultZone: http://localhost:7000/eureka/
server:
   port: 8000

LOG_HOME: logs   
# logging:
#    path: logs
#    file: producer.log
#    level:
#       root: INFO
#       org:
#          eureka:
#             demo:
#                producer: DEBUG
#    pattern:
#       console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#       file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n